name: Fintech Radar Bot (hourly)

on:
  schedule:
    - cron: "0 * * * *"   # запуск каждый час (UTC)
  workflow_dispatch: {}   # ручной запуск из вкладки Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run bot (posts only at target local hour)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          PRODUCTHUNT_TOKEN:  ${{ secrets.PRODUCTHUNT_TOKEN }}
          TIMEZONE:           ${{ secrets.TIMEZONE }}
          POST_AT_HOUR_LOCAL: ${{ secrets.POST_AT_HOUR_LOCAL }}
        run: |
          python bot.py
